### ISSUE TITLE
circleci: Running cucumber with test metadata

### ISSUE THREAD

**Issue by rosskevin** [KnapsackPro/knapsack_pro-ruby#24]
My build works with knapsack and without creating test metadata.  Next, I want to add the test metadata to the builds for better feedback, though I'm running into some issues.

I'm trying to setup our build and obtain circleci test metadata as described:
https://circleci.com/docs/test-metadata/#cucumber

Also related:
https://circleci.com/docs/parallel-manual-setup/#auto-balancing

I've tried various ways of specifying parameters (quotes etc), but in the end I run into:

```
Configure the build00:07cache

modifiers to 'cucumber' must be a map

Action failed: Configure the build
```

My yaml has been verified with yamllint, here's the relevant snippet:

```yaml
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/cucumber:
      parallel: true

    # Step for rspec
    - bundle exec rake knapsack_pro:rspec['--format progress --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml']:
        parallel: true

    # Step for cucumber
    - bundle exec rake knapsack_pro:cucumber['--format pretty --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber']:
        parallel: true
```

How should I be specifying these parameters for rspec and cucumber?

**Comment by ArturT** [comment]
Hi @rosskevin 

You have missed 2 spaces indentation in `mkdir` command and the params for knapsack pro command probably should not be in `'` but the whole command in `"`.

```yaml
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/cucumber:
        parallel: true

    # Step for rspec
    - bundle exec rake "knapsack_pro:rspec[--format progress --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml]":
        parallel: true

    # Step for cucumber
    - bundle exec rake "knapsack_pro:cucumber[--format pretty --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber]":
        parallel: true
```

If that works for you then I recommand to run cucumber first with knapsack_pro regular mode and later run rspec in knapsack_pro queue mode thanks to that you will get better auto balancing.

```yaml
test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/cucumber:
        parallel: true

    # Step for cucumber
    - bundle exec rake "knapsack_pro:cucumber[--format pretty --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber]":
        parallel: true

    # Step for rspec
    - bundle exec rake "knapsack_pro:queue:rspec[--format progress --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml]":
        parallel: true
```

If you will need more help specific for your project you can always email me https://knapsackpro.com/contact :)
