### ISSUE TITLE
 NoMethodError:  undefined method `keys' for nil

### ISSUE THREAD

**Issue by Alagaesia93** [KnapsackPro/knapsack_pro-ruby#242]
Hello!

After bumping version to 7.0 my whole RSpec CI fails with this error
` NoMethodError: undefined method 'keys' for nil`

It must be something connected with dotenv and some env variables, but it started failing only after 7.0 version. I tried to check online, but no luck.

If you need anything else, happy to help!

<details>
  <summary>Full error stack</summary>

```
NoMethodError:
         undefined method `keys' for nil
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/dotenv-3.0.2/lib/dotenv/diff.rb:25:in `added'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/dotenv-3.0.2/lib/dotenv/diff.rb:47:in `any?'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/dotenv-3.0.2/lib/dotenv.rb:78:in `restore'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/dotenv-3.0.2/lib/dotenv/autorestore.rb:9:in `block (2 levels) in <main>'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:372:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:528:in `each'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:614:in `each'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:485:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:518:in `run_after_example'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:283:in `block in run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `block in run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-rails-6.1.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/adapters/rspec_adapter.rb:103:in `block (2 levels) in ensure_no_focus!'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/webmock-3.22.0/lib/webmock/rspec.rb:39:in `block (2 levels) in <main>'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/extensions/rspec_extension.rb:98:in `block (4 levels) in knapsack__run_specs'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/extensions/rspec_extension.rb:96:in `map'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/extensions/rspec_extension.rb:96:in `block (3 levels) in knapsack__run_specs'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/runners/queue/rspec_runner.rb:82:in `block in with_batch'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/runners/queue/rspec_runner.rb:70:in `with_batch'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/extensions/rspec_extension.rb:93:in `block (2 levels) in knapsack__run_specs'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/extensions/rspec_extension.rb:92:in `block in knapsack__run_specs'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/extensions/rspec_extension.rb:91:in `knapsack__run_specs'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/runners/queue/rspec_runner.rb:50:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/knapsack_pro/runners/queue/rspec_runner.rb:20:in `run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/knapsack_pro-7.0.0/lib/tasks/queue/rspec.rake:19:in `block (3 levels) in <main>'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:83:in `block in run'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
       # <filtered>/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
```
</details>

**Comment by ArturT** [comment]
Hi @Alagaesia93 Thank for reporting this.

What Knapsack Pro command do you call? Do you pass any custom options?

Can you share the full txt output from the CI node? You can share it with support at https://knapsackpro.com/contact for confidentiality.

Have you tried upgrading [the dotenv gem](https://github.com/bkeepers/dotenv/blob/main/Changelog.md#303) and rspec-core to the latest version?

Do you have any specific dotenv configuration?

Do you use `config.dotenv.autorestore = true` ([it's a default](https://github.com/bkeepers/dotenv?tab=readme-ov-file#autorestore-in-tests))?

**Comment by Alagaesia93** [comment]
Thank you @ArturT for jumping in so quickly!

ci.yml
```
  rspec:
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    needs: [bundle]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_DB: test_sky_pilot
        ports:
          - 5432/tcp
      redis:
        image: redis
        ports:
          - 6379/tcp
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [3]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0, 1, 2]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build DB
        env:
          PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        run: bin/rails db:schema:load
      - name: Run Rspec Tests
        env:
          PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC }}
          KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
          REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}/1
        run: bin/rake knapsack_pro:queue:rspec
```

not sure what else to add from the CI node, we have hundreds of thousands of tests so it's a gigantic file with the same error repeated for each test :) 

I have dotenv (not dotenv-rails) 3.0.2, released few days ago. I see that there is 3.0.3 with some fixes, I'll run CI again
rspec-rails latest version, rspec-core just 3.12.2 instead of 3.12.3

No specific dotenv config, yes autorestore because it's default

The interesting part is knapsack 6.x works perfectly, knapsack 7.0 breaks everything.
